name: Run Pest tests

on: ['push', 'pull_request']

jobs:
    pest-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['8.3']
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, intl, exif, iconv, fileinfo, xdebug
                  coverage: xdebug

            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader

            - name: Run Pest tests
              run: ./vendor/bin/pest --ci
